language: csharp
solution: HyveLog.sln
install:
  - nuget restore HyveLog.sln
  - nuget install NUnit.Runners -Version 3.8.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug HyveLog.sln
  - mono ./testrunner/NUnit.Runners.3.8.0/tools/nunit-console.exe ./HyveLog/bin/Debug/HyveLog.dll